stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - data/wine_data_raw.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - data/wine_data_raw.csv
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false