stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - data/wine_data_raw.csv
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/wine_data_raw.csv
    outs:
      - data/train_data.csv
      - data/test_data.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train_data.csv
    outs:
      - models/model.joblib

  validate:
    cmd: python validate.py
    deps:
      - validate.py
      - models/model.joblib
      - data/test_data.csv
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false